[CmdletBinding()]
param(
    [string]$OutputDirectory = (Join-Path $PSScriptRoot '..\artifacts\store-package'),
    [ValidateSet('x64','ARM64')][string]$Platform = 'x64',
    [ValidateSet('Debug','Release')][string]$Configuration = 'Release',
    [switch]$ValidationOnly
)

$ErrorActionPreference = 'Stop'
$repo = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$manifestPath = Join-Path $repo 'Package.Store.appxmanifest'
$expectedName = 'JoKiy.PageArc'
$expectedPublisher = 'CN=C4E4B33A-7B77-4121-897C-7D720A5471F8'
$expectedDisplayName = 'Jo Kiyō'
$expectedFamilyName = 'JoKiy.PageArc_4wdwgytaw3v2m'

if (-not (Test-Path $manifestPath)) { throw "Store manifest not found: $manifestPath" }
[xml]$manifest = Get-Content -Raw -LiteralPath $manifestPath
$identity = $manifest.Package.Identity
if ($identity.Name -ne $expectedName) { throw "Store Identity.Name mismatch: $($identity.Name)" }
if ($identity.Publisher -ne $expectedPublisher) { throw "Store Identity.Publisher mismatch: $($identity.Publisher)" }
$display = $manifest.Package.Properties.PublisherDisplayName
if ($display -ne $expectedDisplayName) { throw "Store PublisherDisplayName mismatch: $display" }

$out = [IO.Path]::GetFullPath((Join-Path $repo $OutputDirectory))
New-Item -ItemType Directory -Force -Path $out | Out-Null
$args = @(
    'build', (Join-Path $repo 'PageArc.csproj'), '-c', $Configuration,
    ('-p:Platform=' + $Platform), '--no-restore',
    '-p:PageArcDistributionChannel=Store', '-p:WindowsPackageType=MSIX',
    '-p:GenerateAppxPackageOnBuild=true', '-p:AppxPackageSigningEnabled=false',
    '-p:AppxBundle=Always', ('-p:AppxBundlePlatforms=' + $Platform),
    '-p:UapAppxPackageBuildMode=StoreUpload', '-p:AppxSymbolPackageEnabled=false',
    ('-p:AppxPackageDir=' + ($out.TrimEnd('\') + '\'))
)
if (-not $ValidationOnly) {
    & dotnet @args
    if ($LASTEXITCODE -ne 0) { throw "Store candidate build failed with exit code $LASTEXITCODE" }
}

$packages = @(Get-ChildItem -LiteralPath $out -Filter 'PageArc_*.msix' -Recurse -File)
Add-Type -AssemblyName System.IO.Compression.FileSystem
$bundle = Get-ChildItem -LiteralPath $out -Filter '*.msixbundle' -Recurse -File | Select-Object -First 1
$extractRoot = $null
if ($packages.Count -eq 0 -and $null -ne $bundle) {
    $extractRoot = Join-Path ([IO.Path]::GetTempPath()) ('pagearc-store-bundle-' + [guid]::NewGuid().ToString('N'))
    [IO.Compression.ZipFile]::ExtractToDirectory($bundle.FullName, $extractRoot)
    $packages = @(Get-ChildItem -LiteralPath $extractRoot -Filter 'PageArc_*.msix' -Recurse -File)
}
if ($packages.Count -eq 0) { throw "No MSIX package found under $out" }
$results = foreach ($package in $packages) {
    $zip = [IO.Compression.ZipFile]::OpenRead($package.FullName)
    try {
        $entry = $zip.GetEntry('AppxManifest.xml')
        if ($null -eq $entry) { throw "AppxManifest.xml missing from $($package.Name)" }
        $reader = [IO.StreamReader]::new($entry.Open())
        try { [xml]$packageManifest = $reader.ReadToEnd() } finally { $reader.Dispose() }
        $packageIdentity = $packageManifest.Package.Identity
        [pscustomobject]@{
            File = $package.FullName
            Name = $packageIdentity.Name
            Publisher = $packageIdentity.Publisher
            Version = $packageIdentity.Version
            NameValid = ($packageIdentity.Name -eq $expectedName)
            PublisherValid = ($packageIdentity.Publisher -eq $expectedPublisher)
        }
    } finally { $zip.Dispose() }
}
if ($results.NameValid -contains $false -or $results.PublisherValid -contains $false) {
    $results | Format-Table | Out-String | Write-Error
    throw 'Store package identity validation failed.'
}
$metadata = [ordered]@{
    channel = 'Microsoft Store'
    packageFamilyName = $expectedFamilyName
    identityName = $expectedName
    publisher = $expectedPublisher
    publisherDisplayName = $expectedDisplayName
    storeUploadPackage = if ($null -ne $bundle) { $bundle.FullName } else { $null }
    packages = @($results)
    storeUpload = 'Generated by UapAppxPackageBuildMode=StoreUpload with symbol package generation disabled.'
}
$metadata | ConvertTo-Json -Depth 5 | Set-Content -Encoding utf8 (Join-Path $out 'store-package-validation.json')
$metadata | ConvertTo-Json -Depth 5
if ($null -ne $extractRoot) { Remove-Item -LiteralPath $extractRoot -Recurse -Force -ErrorAction SilentlyContinue }
